name: Get OIDC Token
on: [workflow_dispatch]

jobs:
  oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Request OIDC Token
        run: |
          echo "Requesting OIDC token..."
          curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
               "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value' > oidc_token.txt
          echo "OIDC token saved to oidc_token.txt"
          echo "TOKEN: $(cat oidc_token.txt)"
